USE AB_SD;

CREATE TABLE CONTACT(
	CONTACTID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (CONTACTID),
    FIRSTNAME VARCHAR(100),
    MANAGERID INT
);

CREATE TABLE DIRECTORATE(
	DIRECTORATEID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (DIRECTORATEID),
    ORGID INT,
    CONTACTID INT
);

CREATE TABLE DEPARTMENT(
	DEPARTMENTID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (DEPARTMENTID),
    DIRECTORATEID INT,
    CONTACTID INT
);

CREATE TABLE TEAM(
	TEAMID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (TEAMID),
    DEPARTMENTID INT,
    CONTACTID INT
);

CREATE TABLE REFERENCEDATA(
	REFID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (REFID),
    REFCODE VARCHAR(50),
    REFVALUE VARCHAR(200)
);

CREATE TABLE USER(
	USERID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (USERID),
    ACCOUNT VARCHAR(100),
    EMAIL VARCHAR(200),
    ROLE VARCHAR(200),
    PASSWORD VARCHAR(200)
);

CREATE TABLE TRUSTDISTRICT(
	TRUSTDISTRICTID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (TRUSTDISTRICTID),
    NAME VARCHAR(200),
    DESCRIPTION VARCHAR(256),
    TRUSTREGIONID INT
);

CREATE TABLE SUPPORTINGMATERIAL(
	SUPPORTINGMATERIALID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (SUPPORTINGMATERIALID),
    ORGID INT,
    USERID INT
);

CREATE TABLE TRUSTREGION(
	TRUSTREGIONID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (TRUSTREGIONID),
    NAME VARCHAR(200),
    DESCRIPTION VARCHAR(256),
    COUNTRYID INT
);

CREATE TABLE GOVOFFICEREGION(
	GOVOFFICEREGIONID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (GOVOFFICEREGIONID),
    GOVOFFICEREGIONNAME VARCHAR(200),
    COUNTYID INT,
    COUNTRYID INT
);

CREATE TABLE COUNTRY(
	COUNTRYID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (COUNTRYID),
    COUNTRYNAME VARCHAR(200)
);

CREATE TABLE COUNTY(
	COUNTYID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (COUNTYID, COUNTRYID),
    COUNTRYID INT,
    COUNTYNAME VARCHAR(200)
);

CREATE TABLE TOWN(
	TOWNID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (TOWNID, COUNTYID, COUNTRYID),
    COUNTYID INT,
    COUNTRYID INT,
    TOWNNAME VARCHAR(200)
);

CREATE TABLE ADDRESS(
	ADDRESSID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (ADDRESSID),
    POSTCODE INT,
    TOWNID INT,
    COUNTYID INT,
    COUNTRYID INT
);

CREATE TABLE ORGANISATION(
	ORGID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (ORGID),
    ORGNAME VARCHAR(100),
    CONTACTID INT NOT NULL
);

CREATE TABLE PROGRAMME(
	PROGRAMMEID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (PROGRAMMEID),
    CONTACTID INT
);

CREATE TABLE SERVICE(
	SERVICEID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (SERVICEID),
    CONTACTID INT
);

CREATE TABLE PREMISE(
	PREMISEID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (PREMISEID),
    SERVICEID INT
);

ALTER TABLE CONTACT ADD CONSTRAINT FK_SELF FOREIGN KEY (MANAGERID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE DIRECTORATE ADD CONSTRAINT FK_ORGANISATIONDIRECTORATE FOREIGN KEY (ORGID) REFERENCES ORGANISATION(ORGID);
ALTER TABLE DIRECTORATE ADD CONSTRAINT FK_CONTACTDIRECTORATE FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DIRECTORATEDEPARTMENT FOREIGN KEY (DIRECTORATEID) REFERENCES DIRECTORATE(DIRECTORATEID);
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_CONTACTDEPARTMENT FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE TEAM ADD CONSTRAINT FK_DEPARTMENTTEAM FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID);
ALTER TABLE TEAM ADD CONSTRAINT FK_CONTACTTEAM FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE TRUSTDISTRICT ADD CONSTRAINT FK_TRUSTREGIONTRUSTDISTRICT FOREIGN KEY (TRUSTREGIONID) REFERENCES TRUSTREGION(TRUSTREGIONID);
ALTER TABLE SUPPORTINGMATERIAL ADD CONSTRAINT FK_ORGANISATIONSUPPORTINGMATERIAL FOREIGN KEY (ORGID) REFERENCES ORGANISATION(ORGID);
ALTER TABLE SUPPORTINGMATERIAL ADD CONSTRAINT FK_USERSUPPORTINGMATERIAL FOREIGN KEY (USERID) REFERENCES USER(USERID);
ALTER TABLE ORGANISATION ADD CONSTRAINT FK_CONTACTORGANISATION FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE PROGRAMME ADD CONSTRAINT FK_CONTACTPROGRAMME FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE TRUSTREGION ADD CONSTRAINT FK_COUNTRYTRUSTREGION FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID);
ALTER TABLE GOVOFFICEREGION ADD CONSTRAINT FK_COUNTRYGOVOFFICEREGION FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID);
ALTER TABLE GOVOFFICEREGION ADD CONSTRAINT FK_COUNTYGOVOFFICEREGION FOREIGN KEY (COUNTYID) REFERENCES COUNTY(COUNTYID);
ALTER TABLE SERVICE ADD CONSTRAINT FK_CONTACTSERVICE FOREIGN KEY (CONTACTID) REFERENCES CONTACT(CONTACTID);
ALTER TABLE PREMISE ADD CONSTRAINT FK_SERVICEPREMISE FOREIGN KEY (SERVICEID) REFERENCES SERVICE(SERVICEID);
ALTER TABLE COUNTY ADD CONSTRAINT FK_COUNTRYCOUNTY FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID);
ALTER TABLE TOWN ADD CONSTRAINT FK_COUNTRYTOWN FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID);
ALTER TABLE TOWN ADD CONSTRAINT FK_COUNTYTOWN FOREIGN KEY (COUNTYID) REFERENCES COUNTY(COUNTYID);
ALTER TABLE ADDRESS ADD CONSTRAINT FK_COUNTYADDRESS FOREIGN KEY (COUNTYID) REFERENCES COUNTY(COUNTYID);
ALTER TABLE ADDRESS ADD CONSTRAINT FK_COUNTRYADDRESS FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID);
ALTER TABLE ADDRESS ADD CONSTRAINT FK_TOWNADDRESS FOREIGN KEY (TOWNID) REFERENCES TOWN(TOWNID);